# from johns stuff
if [ -f /etc/zshrc ] && ! command -v nix > /dev/null 2> /dev/null; then
source /etc/zshrc
fi

if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

. ~/.nix-profile/share/zsh-powerlevel10k/powerlevel9k.zsh-theme

# from my stuff
HYPHEN_INSENSITIVE="true"
# don't verify history expansion before execution
unsetopt histverify

# User configuration
setopt extended_glob

eval "$(zoxide init zsh)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Colorizer aliases using grc
[[ -s "/etc/grc.zsh" ]] && source /etc/grc.zsh

# break this out
if [ -f $HOME/.ros_setup ]; then
    . $HOME/.ros_setup
fi

# non shell independent stuff
# run zsh hook
precmd() { eval "$PROMPT_COMMAND" }